# Generated by Django 5.1.4 on 2025-01-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing_comments_bids_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="current_bid",
            field=models.IntegerField(default=0),
        ),
    ]
