# Generated by Django 5.1.6 on 2025-02-24 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_alter_posts_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="likes",
        ),
        migrations.AddField(
            model_name="posts",
            name="likes",
            field=models.ManyToManyField(
                null=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
