# Generated by Django 5.1.6 on 2025-02-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_remove_posts_likes_posts_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="Follower",
            new_name="follower",
        ),
    ]
