# Generated by Django 5.1.6 on 2025-02-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_rename_follower_follow_follower"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
